import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PrismaticBurst from "@/components/PrismaticBurst";
import React from "react";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative`}
      >
      <NavBar/>
      <div className="absolute z-[-1] inset-0 top-0 w-full h-32 min-h-screen">
          <PrismaticBurst
              animationType="rotate3d"
              intensity={2}
              speed={0.5}
              distort={1.0}
              paused={false}
              offset={{ x: 0, y: 0 }}
              hoverDampness={0.25}
              rayCount={24}
              mixBlendMode="lighten"
              colors={['#ff007a', '#4d3dff', '#ffffff']}
          />
      </div>
      <main>{children}</main>
      </body>
    </html>
  );
}
